# .github/FUNDING.yml

# GitHub Sponsors (fino a 4 utenti)
github: [dan-74]

# Opzionali (decommenta e sostituisci con i tuoi handle)
# patreon: your_patreon
# open_collective: your_collective
# ko_fi: your_kofi
# tidelift: platform-name/package-name   # es. npm/babel
# community_bridge: project-name
# liberapay: your_liberapay
# issuehunt: your_issuehunt
# lfx_crowdfunding: project-name
# polar: your_polar
# buy_me_a_coffee: your_bmac
# thanks_dev: your_thanks_dev

# URL personalizzati (max 4). Devono essere https://
# custom: ['https://your-landing-page.example', 'https://your-donate-link.example']

