name: 02-lint
on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

permissions:
  contents: read
  security-events: write
  actions: read
  checks: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install Python deps
        run: |
          python -m pip install -U pip
          pip install -e .[dev]

      # Doppio step installazione Node
      - name: Install Node deps (ci)
        if: ${{ hashFiles('package-lock.json') != '' }}
        run: npm ci

      - name: Install Node deps (no lockfile)
        if: ${{ hashFiles('package-lock.json') == '' }}
        run: npm install

      - name: Ruff
        run: ruff check .

      - name: Black (check)
        run: black --check .

      # ESLint solo se esistono file .ts/.js
      - name: ESLint
        if: ${{ hashFiles('**/*.ts') != '' || hashFiles('**/*.js') != '' }}
        run: eslint .

      # Markdownlint solo se ci sono .md
      - name: Markdownlint
        if: ${{ hashFiles('**/*.md') != '' }}
        run: markdownlint **/*.md

      - name: Yamllint
        run: yamllint .
