name: 06-security
on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
permissions:
  contents: read
  security-events: write
  actions: read
  checks: write
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - uses: actions/setup-node@v4
        with: { node-version: "22" }
      - run: pip install -e .[dev]
      - run: npm ci
      - name: Semgrep
        run: semgrep --config .semgrep.yml
      - name: Bandit
        run: bandit -q -r src
      - name: Detect Secrets
        run: detect-secrets scan --all-files
